spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-soft-wildflower-ai8hho90-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${DATABASE_USERNAME:neondb_owner}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
server:
  port: 8080
app:
  jwt:
    secret: ${JWT_SECRET:VGhpc0lzQURldk9ubHlKZXd0U2VjcmV0S2VlcEl0TG9uZ0FuZFNlY3VyZQ==}

google:
  client-id: ${GOOGLE_CLIENT_ID:your-client-id}
  client-secret: ${GOOGLE_CLIENT_SECRET:your-client-secret}
  redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/auth/google/callback}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:ddzvrbvgk}
  api-key: ${CLOUDINARY_API_KEY:175621781666645}
  api-secret: ${CLOUDINARY_API_SECRET:flEYHfTzkWt4irWlYqtwn1Uy77k}
